name: Continous integration & deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  Dev:
    name: Deploy to Dev 
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: dev
    steps:
      - name: Deploy
        run: echo I am deploying! 
  SIT:
    name: Deploy to SIT 
    runs-on: ubuntu-latest
    needs: build
    environment: 
       name: sit
    steps:
      - name: Deploy
        run: echo I am deploying in SIT!

  UAT:
    name: Deploy to UAT 
    runs-on: ubuntu-latest
    needs: SIT
    environment: 
       name: uat
    steps:
      - name: Deploy
        run: echo I am deploying in UAT!      
        
  Stag:
    name: Deploy to Stagging
    runs-on: ubuntu-latest
    needs: UAT
    environment: 
      name: stagging
    steps:
      - name: Deploy
        run: echo I am deploying in stagging!  
  
  Production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: Stag
    environment: 
      name: prod
    steps:
      - name: Deploy
        run: echo I am deploying in Product!
