name: Build Web Api
on: 
  push:
    branches : ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.0.x
  
      - name: restore dependencies
        run: dotnet restore
        
      - name: build
        run: dotnet build --no-restore
  
      - name: dotnet publish
        run: dotnet publish GitHubPocWebAPI/GitHubPocWebAPI.csproj -c release -o ${{env.DOTNET_ROOT}}/githubpocapi
  
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3.1.2
        with:
          name: githubpoc.api
          path: ${{env.DOTNET_ROOT}}/githubpocapi/**

  Developement:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with: 
          name: githubpoc.api
          
      - name: Deploy to Dev
        run: echo I am deploying!
        
  SIT:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with: 
          name: githubpoc.api
        
      - name: Deploy to Sit
        run: echo I am deploying in SIT!

  UAT:
      runs-on: ubuntu-latest
      needs: SIT
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with: 
            name: githubpoc.api
          
        - name: Deploy to Uat
          run: echo I am deploying in UAT!

  STAG:
      runs-on: ubuntu-latest
      needs: UAT
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with: 
            name: githubpoc.api
          
        - name: Deploy to Stag
          run: echo I am deploying in STAG!

  PROD:
      runs-on: ubuntu-latest
      needs: STAG
      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with: 
            name: githubpoc.api
          
        - name: Deploy to Prod
          run: echo I am deploying in PROD!        
      
